const newProducts = {
  E3: {
    Colour: "Gray",
    "Model Number": "Model No. E3",
    "Screen Size and Resolution": "15.6inch, full HD 1920*1080",
    "Screen Type": "full HD display, Anti-Glare, 250 nits, 45% NTSC",
    Processor: "Intel i5-13th generation",
    "Core, threads and caching": "4 Core, 8 Threads, catch 8 MB",
    "Processor frequency": "2.4Ghz to Turbo 4.2Ghz",
    "Graphic Memory": "Intel Iris Xe Graphics 1GB",
    User: "Business and General user ",
    RAM: "one slot DDR4 -8GB/16GB",
    "Storage memory": "One M.2 Nvme 512GB /1TB SSD",
    "Fingerprint reader": "Yes, located on touchpad",
    "Operating system": "Pre-Installed Window 11 Pro",
    "MS office provided": "Yes",
    "Wi-Fi": "M.2 interface, 802.11 a/b/g/n/a 2.4G and 5G Dual Band",
    Bluetooth: "4.2 version",
    USB: "2 USB2.0 and 2 USB 3.0/3.1, Type C",
    HDMI: "HDMI, Support 4K 24HZ",
    "Memory card": "Yes, one SD-MMC card Slot",
    "Earphone port": "3.5mm jack, Mic in/Line Out",
    Mic: "Bulit-in, Analog microphone",
    speaker: "Built-in 8Ω/0.8W speaker",
    Webcam: "Yes, 2.0Mmeet",
    Touchpad: "Yes, extra Large",
    Keyboard: "100Keys, Backlit Keyboard, With Independent Numeric Keyboard.",
    Weight: "1.8KG",
    "Power button": "One Cherry mechanical key power button",
    Power: "DC jack ∮5.52.5mm power interface",
    Battery: "5000mah, 57.75Wh/11.4V, 3 Cells Lithium-ion polymer battery",
    "Power Adaptor": "Input:100-240V-50/60Hz, Output: 19.0V",
    "Reset Key for recovery": "One reset key",
    "Warranty Period": "1Year Onsite Warranty",
    "Warranty Type": "Onsite and Pick and Drop",
    "Covered in Warranty": "Manufacturing Defects, Physical Damage not covered",
    "Included in Box": "Laptop, Power Cord, Adapter, User manual, Laptop Bag,",
    "Manufacturer Name": "ENTION Technology and Services Pvt. Ltd.",
    Country: "Made in India",
  },
  E4: {
    Colour: "Gray",
    "Model Number": "Model No. E4",
    "Screen Size and Resolution":
      "15.6 inch, 1920*1080 IPS 16:9 ratio, 250Cd/m2 Brightness",
    "Screen Type": "full HD",
    Processor: "intel i7 13620 H/ intel i5 1235U",
    "Core, threads and caching": "10 Cores, 16 Threads, 24MB intel smart cache",
    "Processor frequency": "upto 4.90GHz",
    "Graphic Memory": "Intel UHD Graphics 1.50GHz",
    User: "High end user",
    RAM: "8/16/32/64GB DDR4(DIMM 2Slots) 32MT/S",
    "Storage memory": "SSD 512GB/1TB/2TB support upto 4TB, 2Nvme PCIE4.0 slots",
    "Fingerprint reader": "Yes, located on touchpad",
    "Operating system": "Pre - installed Window 11",
    "MS office provided": "Yes, 365",
    "Wi-Fi": "WiFi 802.11, ax",
    Bluetooth: "Bluetooth 4.2 , 5.2",
    USB: "3 port of USB3.2 gen1, 5Gbps, Type C(Data+DP+charging)",
    HDMI: "HDMI A Type",
    RJ45: "Yes",
    "Memory card": "1Micro SD card Upto 128Gb",
    "Earphone port": "3.5 mm standard headphone jack",
    Mic: "Bulit-in, Analog microphone",
    speaker: "Builf=t in stereo speaker 1.0W*2",
    Webcam: "2.0Mega+DMIC, with Privcay sutter",
    Touchpad: "Yes, extra Large",
    Keyboard: "US, Round with Backlight & Square with Backlight",
    "Product Dimension": "357.4*228*19 mm",
    Weight: "1.67KG",
    "Power button": "on Keyboard",
    Power: "DC 19V/3.42A",
    Battery: "5000Mah",
    "Power Adaptor": "19V, 65W",
    "Reset Key for recovery": "No",
    "Warranty Period": " 18 Months Onsite Warranty",
    "Warranty Type": "Onsite",
    "Covered in Warranty": "Manufacturing Defects, Physical Damage not covered",
    "Included in Box": "Laptop, Power Cord, Adapter, User Manual, Laptop Bag",
    "Manufacturer Name": "ENTION Technology and Services Pvt. Ltd.",
    Country: "Made in India",
  },
  E5: {
    Colour: "Sliver",
    "Model Number": "Model No. E5",
    "Screen Size and Resolution": "15.6 inch, full HD",
    "Screen Type": "15.6 inch, 1920*1080 IPS 16:9 ratio, 250Cd/m2 Brightness",
    Processor: "intel N-95 processor",
    "Core, threads and caching": "4Core, 4Threads, ",
    "Processor frequency": "upto 3.40Ghz",
    "Graphic Memory": "intel UHD graphics 1.20GHz",
    User: "General, Student, Learner",
    RAM: "8/16/32GB",
    "Storage memory": "512GB/1TB/2TB",
    "Fingerprint reader": "Yes, on Touch Pad",
    "Operating system": "window 11",
    "MS office provided": "yes, 365",
    "Wi-Fi": "WiFi 802.11 A",
    Bluetooth: "Bluetooth 4.0",
    USB: "3 port of USB3.0, 5Gbps, Type C(Data+DP)",
    HDMI: "HDMI A Type",
    RJ45: "Yes",
    "Memory card": "1Micro SD card Upto 128Gb",
    "Earphone port": "3.5 mm standard headphone jack",
    Mic: "Built in Analog microphone",
    speaker: "Builf=t in stereo speaker 1.0W*2",
    Webcam: "2.0Mega+DMIC, with Privcay sutter",
    Touchpad: "Yes, extra large",
    Keyboard: "US, Round with Backlight & Square with Backlight",
    "Product Dimension": "357.4*228*19 mm",
    Weight: "1.68Kg",
    "Power button": "on Key Board",
    Power: "DC 12V/1.5V",
    Battery: "5000 mAH",
    "Power Adaptor": "12V",
    "Reset Key for recovery": "One reset key",
    "Warranty Period": "18 Months  Onsite Warranty",
    "Warranty Type": "Onsite",
    "Covered in Warranty": "Manufacturing Defects, Physical Damage not covered",
    "Included in Box": "Laptop, Power Cord, Adapter, User Manual, Laptop Bag",
    "Manufacturer Name": "ENTION Technology and Services Pvt. Ltd.",
    Country: "Made in India",
  },
};

export default newProducts;
