const products = [
  {
    title: 'Intel® i7-12th Gen',
    slug: 'intel-i7-12th-generation-ention-workbook-e3-series',
    content: '',
    description:
      'Intel® Core™ i7 processors hybrid architecture with up to eight Performance-cores, positioned at top of the of the Intel® Core™ family processor. It generally has more cores, larger cache sizes, higher clock speed with boundary breaking performance. Preferred for high end user, gamers, video editing work.',
    category: 'Intel® i7 Processor Laptop',
    pricing: {
      sellingPrice: 89990,
      mrp: 99990,
      discount: 20,
    },
    variant: {
      '8GB RAM + 512GM SSD': 'Rs. .................',
      '8GB RAM + 1TB SSD': 'Rs. .................',
      '16GB RAM + 512GB SSD': 'Rs. ............',
      '16GB RAM + 1TB SSD': 'Rs. ............',
    },

    cover_image: '/assets/E3/e3_1.svg',

    images: [
      '/assets/E3/e3_2.svg',
      '/assets/E3/e3_3.svg',
      '/assets/E3/e3_4.svg',
      '/assets/E3/e3_5.svg',
      '/assets/E3/e3_6.svg',
      '/assets/E3/e3_7.svg',
      '/assets/E3/e3_8.svg',
      '/assets/E3/e3_9.svg',
      '/assets/E3/e3_10.svg',
      '/assets/E3/e3_11.svg',

      '/assets/E3/e3_12.svg',
    ],
    videos: [
      // "/assets/e3_i7_12_gen.mp4"
      '/assets/E3.mp4',
    ],
    specifications: {
      Colour: 'Gray',
      'Model Number': 'Model No. E3',
      'Screen Size and Resolution': '15.6inch, full HD 19201080',
      'Screen Type': 'full HD display, Anti-Glare, 250 nits, 45% NTSC',
      Processor: 'Intel® i7- 12th generation 1260P',
      'Core, threads and caching':
        '12Core, 16Threads, 18 MB Intel® Smart Cache',
      'Processor frequency': '2.8Ghz to Turbo 4.7Ghz',
      'Graphic Memory': 'Intel® Iris Xe Graphics 1GB',
      User: 'High end user',
      RAM: 'one slot DDR4 -8GB/16GB/32GB',
      'Storage memory': 'One M.2 Nvme 512GB/1TB SSD',
      'Fingerprint reader': 'Yes, located on touchpad',
      'Operating system': 'Pre-Installed Window 11',
      'MS office provided': 'Yes',
      'Wi-Fi': 'M.2 interface, 802.11 a/b/g/n/a 2.4G and 5G Dual Band',
      Bluetooth: '4.2 version',
      USB: '2 USB2.0 and 2 USB 3.0/3.1, Type C',
      HDMI: 'HDMI, Support 4K 24HZ',
      'RJ45 LAN': 'Yes, one RJ45 LAN',
      'Memory card': 'Yes, one SD-MMC Card Slot',
      'Earphone port': '3.5mm jack, Mic in/Line Out',
      Mic: 'Bulit-in, Analog microphone',
      speaker: 'Built-in 8Ω/0.8W speaker',
      Webcam: 'Yes, 2.0Mmeet',
      Touchpad: 'Yes, extra Large',
      Keyboard: ' Backlit Keyboard, With Independent Numeric Keyboard.',
      'Product Dimension': '360mm*240mm*15mm',
      Weight: '1.8KG',
      'Power button': 'One Cherry mechanical key power button',
      Power: 'DC jack ∮5.52.5mm power interface',
      Battery: '5000mah, 57.75Wh/11.4V, 3 Cells Lithium-ion polymer battery',
      'Power Adaptor': 'Input:100-240V-50/60Hz, Output: 19.0V',
      'Reset Key for recovery': 'One reset key',
      'Warranty Period': '18 Months Onsite Warranty',
      'Warranty Type': 'Onsite Warranty',
      'Covered in Warranty':
        'Manufacturing Defects, Physical Damage not covered',
      'Included in Box': 'Laptop, Power Cord, Adapter, User manual, Laptop Bag',
      'Manufacturer Name': 'Ention™ Technology and Services Pvt. Ltd.',
      Country: 'Made in India',
    },
    pdf: '/assets/E-3 i7 12gen.pdf',
  },
  {
    title: 'Intel® i7-11th Gen',
    slug: 'intel-i7-11th-generation-ention-workbook-e3-series',
    content:
      'Intel® Core™ i7 processors hybrid architecture with up to eight Performance-cores, positioned at top of the of the Intel® Core™ family processor. It generally has more cores, larger cache sizes, higher clock speed with boundary breaking performance. Preferred for high end user, gamers, video editing work.',
    description:
      'Intel® Core™ i7 processors hybrid architecture with up to eight Performance-cores, positioned at top of the of the Intel® Core™ family processor. It generally has more cores, larger cache sizes, higher clock speed with boundary breaking performance. Preferred for high end user, gamers, video editing work.',
    category: 'Intel® i7 Processor Laptop',
    pricing: {
      sellingPrice: 79990,
      mrp: 89990,
      discount: 20,
    },

    variant: {
      '8GB RAM + 512GM SSD': 'Rs. .................',
      '8GB RAM + 1TB SSD': 'Rs. ................',
      '16GB RAM + 512GB SSD': 'Rs. ............',
      '16GB RAM + 1TB SSD': 'Rs. ............',
    },
    cover_image: '/assets/Products/E3/e3_2.svg',
    images: [
      '/assets/E3/e3_2.svg',
      '/assets/E3/e3_3.svg',
      '/assets/E3/e3_4.svg',
      '/assets/E3/e3_5.svg',
      '/assets/E3/e3_6.svg',
      '/assets/E3/e3_7.svg',
      '/assets/E3/e3_8.svg',
      '/assets/E3/e3_9.svg',
      '/assets/E3/e3_10.svg',
      '/assets/E3/e3_11.svg',

      '/assets/E3/e3_12.svg',
    ],
    videos: [
      // "/assets/e3_i7_11_gen_.mp4"
      '/assets/E3.mp4',
    ],
    specifications: {
      Colour: 'Gray',
      'Model Number': 'Model No. E3',
      'Screen Size and Resolution': '15.6inch, full HD 19201080',
      'Screen Type': 'full HD display, Anti-Glare, 250 nits, 45% NTSC',
      Processor: 'Intel® i7- 11th generation 1165G7',
      'Core, threads and caching': '4 Core, 8 Threads, catch 12MB',
      'Processor frequency': '2.8Ghz to Turbo 4.7Ghz',
      'Graphic Memory': 'Intel® Iris Xe Graphics 1GB',
      User: 'Hing end user',
      RAM: 'one slot DDR4 -8GB/16GB',
      'Storage memory': 'One M.2 Nvme 512GB/1TB SSD',
      'Fingerprint reader': 'Yes, located on touchpad',
      'Operating system': 'Pre-Installed Window 11',
      'MS office provided': 'Yes',
      'Wi-Fi': 'M.2 interface, 802.11 a/b/g/n/a 2.4G and 5G Dual Band',
      Bluetooth: '4.2 version',
      USB: '2 USB2.0 and 2 USB 3.0/3.1, Type C',
      HDMI: 'HDMI, Support 4K 24HZ',
      'Memory card': 'Yes, one SD-MMC Card Slot',
      'Earphone port': '3.5mm jack, Mic in/Line Out',
      Mic: 'Bulit-in, Analog microphone',
      speaker: 'Built-in 8Ω/0.8W speaker',
      Webcam: 'Yes, 2.0Mmeet',
      Touchpad: 'Yes, extra Large',
      Keyboard: ' Backlit Keyboard, With Independent Numeric Keyboard.',
      'Product Dimension': '360mm*240mm*15mm,',
      Weight: '1.8KG',
      'Power button': 'One Cherry mechanical key power button',
      Power: 'DC jack ∮5.52.5mm power interface',
      Battery: '5000mah, 57.75Wh/11.4V, 3 Cells Lithium-ion polymer battery',
      'Power Adaptor': 'Input:100-240V-50/60Hz, Output: 19.0V',
      'Reset Key for recovery': 'One reset key',
      'Warranty Period': ' 18 Months Onsite Warranty',
      'Warranty Type': 'Onsite Warranty',
      'Covered in Warranty':
        'Manufacturing Defects, Physical Damage not covered',
      'Included in Box': 'Laptop, Power Cord, Adapter, User manual, Laptop Bag',
      'Manufacturer Name': 'Ention™ Technology and Services Pvt. Ltd.',
      Country: 'Made in India',
    },
    pdf: '/assets/E-3 i7 11gen.pdf',
  },
  {
    title: 'Intel® i5-12th Gen',
    slug: 'intel-i5-12th-generation-ention-workbook-156inch',
    content: '',
    description:
      'Intel® Core™ i5 processors typically have multiple cores, that handle intense multitasking, delivered high speed in smooth way with. Computing experience made smarter with excellent powerful performance for business user, professional, general user.',

    category: 'Intel® i5 Processor Laptop',
    pricing: {
      sellingPrice: 69990,
      mrp: 79990,
      discount: 20,
    },
    variant: {
      '8GB RAM + 512GM SSD': 'Rs. .................',
      '8GB RAM + 1TB SSD': 'Rs. ................',
      '16GB RAM + 512GB SSD': 'Rs. ................',
      '16GB RAM + 1TB SSD': 'Rs. ................',
    },
    cover_image: '/assets/Products/E3/e3_7.svg',
    images: [
      '/assets/E3/e3_2.svg',
      '/assets/E3/e3_3.svg',
      '/assets/E3/e3_4.svg',
      '/assets/E3/e3_5.svg',
      '/assets/E3/e3_6.svg',
      '/assets/E3/e3_7.svg',
      '/assets/E3/e3_8.svg',
      '/assets/E3/e3_9.svg',
      '/assets/E3/e3_10.svg',
      '/assets/E3/e3_11.svg',

      '/assets/E3/e3_12.svg',
    ],
    videos: [
      // "/assets/e3_12_gen.mp4"
      '/assets/E3.mp4',
    ],
    specifications: {
      Brand: 'ENTION',
      'Series Name': 'Workbook',
      'Model Number': 'Model No. E3',
      'Sub model Number': '',
      Material: 'Metal',
      Colour: 'Gray',
      'Screen Size and Resolution': '15.6inch, full HD 19201080',
      'Screen Type': 'full HD display, Anti-Glare, 250 nits, 45% NTSC',
      Processor: 'Intel® i5-12th generation',
      'Core, threads and caching': '4 Core, 8 Threads, catch 12MB',
      'Processor frequency': '2.4Ghz to Turbo 4.4Ghz',
      'Graphic Memory': 'Intel® Iris Xe Graphics 1GB',
      User: 'Business and General user',
      RAM: 'one slot DDR4 -8GB/16GB',
      'Storage memory': 'One M.2 Nvme 512GB /1TB SSD',
      'Fingerprint reader': 'Yes, located on touchpad',
      'Operating system': 'Pre-Installed Window 11',
      'MS office provided': 'Yes',
      'Wi-Fi': 'M.2 interface, 802.11 a/b/g/n/a 2.4G and 5G Dual Band',
      Bluetooth: '4.2 version',
      USB: '2 USB2.0 and 2 USB 3.0/3.1, Type C',
      'RJ 45': 'Yes, for better connectivity',
      HDMI: 'HDMI, Support 4K 24HZ',
      'Memory card': 'Yes, one SD-MMC card Slot',
      'Earphone port': '3.5mm jack, Mic in/Line Out',
      Mic: 'Bulit-in, Analog microphone',
      speaker: 'Built-in 8Ω/0.8W speaker',
      Webcam: 'Yes, 2.0Mmeet',
      Touchpad: 'Yes, extra Large',
      Keyboard: ' Backlit Keyboard, With Independent Numeric Keyboard.',
      'Product Dimension': '360mm*240mm*15mm,',
      Weight: '1.8KG',
      'Power button': 'One Cherry mechanical key power button',
      Power: 'DC jack ∮5.52.0mm power interface',
      Battery: '5000mah, 57.75Wh/11.4V, 3 Cells Lithium-ion polymer battery',
      'Power Adaptor': 'Input:100-240V-50/60Hz, Output: 19.0V',
      'Reset Key for recovery': 'One reset key',
      'Warranty Period': '18 Months Onsite Warranty',
      'Warranty Type': 'Onsite Warranty',
      'Covered in Warranty':
        'Manufacturing Defects, Physical Damage not covered',
      'Included in Box': 'Laptop, Power Cord, Adapter, User manual, Laptop Bag',
      'Manufacturer Name': 'Ention™ Technology and Services Pvt. Ltd.',
      Country: 'Make in India',
    },

    pdf: '/assets/E-3 i5 12gen.pdf',
  },
  {
    title: 'Intel® i5-11th Gen',
    slug: 'intel-i5-11th-generation-ention-workbook-156inch',
    content:
      'Intel® Core™ i5 processors typically have multiple cores, that handle intense multitasking, delivered high speed in smooth way with. Computing experience made smarter with excellent powerful performance for business user, professional, general user.',
    description:
      'Intel® Core™ i5 processors typically have multiple cores, that handle intense multitasking, delivered high speed in smooth way with. Computing experience made smarter with excellent powerful performance for business user, professional, general user.',

    category: 'Intel® i5 Processor Laptop',
    pricing: {
      sellingPrice: 69990,
      mrp: 79990,
      discount: 20,
    },
    variant: {
      '8GB RAM + 512GM SSD': 'Rs. .................',
      '8GB RAM + 1TB SSD': 'Rs. ................',
      '16GB RAM + 512GB SSD': 'Rs. ................',
      '16GB RAM + 1TB SSD': 'Rs. ................',
    },

    cover_image: '/assets/Products/E3/e3_8.svg',
    images: [
      '/assets/E3/e3_2.svg',
      '/assets/E3/e3_3.svg',
      '/assets/E3/e3_4.svg',
      '/assets/E3/e3_5.svg',
      '/assets/E3/e3_6.svg',
      '/assets/E3/e3_7.svg',
      '/assets/E3/e3_8.svg',
      '/assets/E3/e3_9.svg',
      '/assets/E3/e3_10.svg',
      '/assets/E3/e3_11.svg',

      '/assets/E3/e3_12.svg',
    ],
    videos: [
      // "/assets/e3_11gen.mp4"
      '/assets/E3.mp4',
    ],
    specifications: {
      Brand: 'ENTION',
      'Series Name': 'Workbook',
      'Model Number': 'Model No. E3',
      'Sub model Number': '',
      Material: 'Metal',
      Colour: 'Gray',
      'Screen Size and Resolution': '15.6inch, full HD 19201080',
      'Screen Type': 'full HD display, Anti-Glare, 250 nits, 45% NTSC',
      Processor: 'Intel® i5-11th generation 1135G7',
      'Core, threads and caching': '4 Core, 8 Threads, catch 8 MB',
      'Processor frequency': '2.4Ghz to Turbo 4.2Ghz',
      'Graphic Memory': 'Intel® Iris Xe Graphics 1GB',
      User: 'Business and General user',
      RAM: 'one slot DDR4 -8GB/16GB',
      'Storage memory': 'One M.2 Nvme 512GB /1TB SSD',
      'Fingerprint reader': 'Yes, located on touchpad',
      'Operating system': 'Pre-Installed Window 11',
      'MS office provided': 'Yes',
      'Wi-Fi': 'M.2 interface, 802.11 a/b/g/n/a 2.4G and 5G Dual Band',
      Bluetooth: '4.2 version',
      USB: '2 USB2.0 and 2 USB 3.0/3.1, Type C',
      HDMI: 'HDMI, Support 4K 24HZ',
      'Memory card': 'Yes, one SD-MMC card Slot',
      'Earphone port': '3.5mm jack, Mic in/Line Out',
      Mic: 'Bulit-in, Analog microphone',
      speaker: 'Built-in 8Ω/0.8W speaker',
      Webcam: 'Yes, 2.0Mmeet',
      Touchpad: 'Yes, extra Large',
      Keyboard: ' Backlit Keyboard, With Independent Numeric Keyboard.',
      'Product Dimension': '360mm*240mm*15mm,',
      Weight: '1.8KG',
      'Power button': 'One Cherry mechanical key power button',
      Power: 'DC jack ∮5.52.0mm power interface',
      Battery: '5000mah, 57.75Wh/11.4V, 3 Cells Lithium-ion polymer battery',
      'Power Adaptor': 'Input:100-240V-50/60Hz, Output: 19.0V',
      'Reset Key for recovery': 'One reset key',
      'Warranty Period': '18 Months Onsite Warranty',
      'Warranty Type': 'Onsite Warranty',
      'Covered in Warranty':
        'Manufacturing Defects, Physical Damage not covered',
      'Included in Box': 'Laptop, Power Cord, Adapter, User manual, Laptop Bag',
      'Manufacturer Name': 'Ention™ Technology and Services Pvt. Ltd.',
      Country: 'Make in India',
    },
    pdf: '/assets/E-3 i5 11gen.pdf',
  },

  {
    title: 'Ryzon R5 4700 Gen',
    slug: 'ryzon-r5-4700-generation',
    content:
      'AMD Ryzen5 is a family of mid- range performance 64bit quad core processors with frequency up to 4.0Ghz. processor Bring outstanding energy efficiency and graphics processing capabilities, helping you meet complex office needs, daily work, learning, and entertainment usage.',
    description:
      'AMD Ryzen5 is a family of mid- range performance 64bit quad core processors with frequency up to 4.0Ghz. processor Bring outstanding energy efficiency and graphics processing capabilities, helping you meet complex office needs, daily work, learning, and entertainment usage.',
    category: 'AMD R5 Processor Laptop',
    pricing: {
      sellingPrice: 49990,
      mrp: 59990,
      discount: 20,
    },

    variant: {
      '12GB RAM + 512GM SSD': 'Rs. .................',
      '12GB RAM + 1TB SSD': 'Rs. ................',
      '18GB RAM + 512GB SSD': 'Rs. ............',
      '18GB RAM + 1TB SSD': 'Rs. ............',
    },
    cover_image: '/assets/Products/E2/e2_5.svg',
    images: [
      '/assets/E2/e2_1.svg',
      '/assets/E2/e2_2.svg',
      '/assets/E2/e2_3.svg',
      '/assets/E2/e2_4.svg',
      '/assets/E2/e2_5.svg',
      '/assets/E2/e2_6.svg',
      '/assets/E2/e2_7.svg',
      '/assets/E2/e2_8.svg',
      '/assets/E2/e2_9.svg',
      '/assets/E2/e2_10.svg',
      '/assets/E2/e2_11.svg',
    ],
    videos: [
      // "/assets/ention_e2_.mp4"
      '/assets/E2.mp4',
    ],
    specifications: {
      Brand: 'ENTION',
      'Series Name': 'Workbook',
      'Model Number': 'Model No. E2',
      Material: 'High grade Plastic',
      Colour: 'Sliver',
      'Screen Size and Resolution': '14inch, full HD 19201080',
      'Screen Type': 'Full HD display',
      Processor: 'Intel® J4105',
      'Core, threads and caching': '4 core, 4 threads',
      'Processor frequency': '1.50GHz to 2.550GHz',
      'Graphic Memory': 'Intel® UHD Graphics 600',
      User: 'Student, General',
      RAM: 'DDR4- 6GB on Board',
      'Storage memory': '512GB SSD',
      'Fingerprint reader': 'NA',
      'Operating system': 'Pre-Installed Window 11',
      'MS office provided': 'Yes,',
      'Wi-Fi': '802.11B/G/N',
      Bluetooth: '4.0 version',
      USB: '2 USB 3.0',
      HDMI: 'Mini HDMI',
      'Memory card': 'Yes, one Micro SD port',
      'Earphone port': '3.5mm jack, Mic in/Line Out',
      Mic: 'Bulit-in, 2 Analog microphone',
      speaker: 'Built-in 8Ω/0.8W speaker x 2',
      Webcam: 'Yes',
      Touchpad: 'Yes',
      Keyboard: 'Without independent Numeric keys',
      'Product Dimension': '360mm*240mm*15mm',
      Weight: '1.2KG',
      'Power button': 'Power button on keyboard',
      Power: 'DC jack ∮5.51.5mm power interface',
      Battery: '4500mah, 2 cell Lithium-ion polymer battery',
      'Power Adaptor': 'Input:100-240V-50/60Hz, Output: 12V',
      'Reset Key for recovery': 'NA',
      'Warranty Period': '18 Months Onsite Warranty',
      'Warranty Type': 'Onsite Warranty',
      'Covered in Warranty':
        'Manufacturing Defects, Physical Damage not covered',
      'Included in Box': 'Laptop, Power Cord, Adapter, User manual, Laptop Bag',
      'Manufacturer Name': 'Ention™ Technology and Services Pvt. Ltd.',
      Country: 'Make in India',
    },
    pdf: '/assets/E2 AMD R5 .pdf',
  },

  {
    title: 'Intel J 4105 Gen',
    slug: 'intel-j-4105-generation',
    content:
      'Intel® Core™ J4105 quad core processor having fan less colling system and gives frequency up to 2.5oGhz, preferred for day to day works, and student purpose. Intel® Core™ J series processor often used in budget friendly laptop. ',
    description:
      'Intel® Core™ J4105 quad core processor having fan less colling system and gives frequency up to 2.5oGhz, preferred for day to day works, and student purpose. Intel® Core™ J series processor often used in budget friendly laptop. ',

    category: 'Intel® J Series Processor Laptop',
    pricing: {
      sellingPrice: 39990,
      mrp: 49990,
      discount: 20,
    },

    variant: {
      '6GB RAM + 512GM SSD': 'Rs. .................',
      '6GB RAM + 1TB SSD': 'Rs. ................',
    },
    cover_image: '/assets/Products/E1/e1_2.svg',
    images: [
      '/assets/E1/e1_1.svg',
      '/assets/E1/e1_2.svg',
      '/assets/E1/e1_3.svg',
      '/assets/E1/e1_4.svg',
      '/assets/E1/e1_5.svg',
      '/assets/E1/e1_6.svg',
      '/assets/E1/e1_7.svg',
      '/assets/E1/e1_8.svg',
      '/assets/E1/e1_9.svg',
      '/assets/E1/e1_10.svg',
      '/assets/E1/e1_11.svg',
      '/assets/E1/e1_12.svg',
      '/assets/E1/e1_13.svg',
    ],
    videos: ['/assets/Ention E1.mp4'],
    specifications: {
      Brand: 'ENTION',
      'Series Name': 'Workbook',
      'Model Number': 'Model No. E1',
      Material: 'Metal',
      Colour: 'sliver',
      'Screen Size and Resolution': '15.6inch, full HD 1920*1080',
      'Screen Type': 'Full HD display with Narrow Bezel',
      Processor: 'AMD Ryzen R5-4500U',
      'Core, threads and caching': '6Core, 6Threads, and L2- 3MB, L3-8MB',
      'Processor frequency': '2.3Ghz to Turbo 4.0Ghz',
      'Graphic Memory': 'Integrated AMD Radeon Graphics',
      User: 'Business and General user',
      RAM: 'DDR4- 4GB on Board, with additional slot',
      'Storage memory': '512GB SSD',
      'Fingerprint reader': 'Yes, located on touchpad',
      'Operating system': 'Pre-Installed Window 11',
      'MS office provided': 'Yes',
      'Wi-Fi': 'M.2 interface, 802.11 a/b/g/n/a 2.4G and 5G Dual Band',
      Bluetooth: '4.2 Version',
      USB: '2 USB2.0 and 2 USB 3.0/3.1, Type C',
      HDMI: 'HDMI',
      'Memory card': 'Yes, one SD card slot',
      'Earphone port': '3.5mm jack, Mic in/Line Out',
      Mic: 'Bulit-in, 2 Analog microphone',
      speaker: 'Built-in 8Ω/0.8W speaker',
      Webcam: 'Yes',
      Touchpad: 'Yes, extra Large',
      Keyboard: ' With Independent Numeric Keyboard.',
      'Product Dimension': '360mm*240mm*15mm',
      Weight: '1.7KG',
      'Power button': 'Power button on keyboard',
      Power: 'DC jack ∮5.52.0mm power interface',
      Battery: '5000mah, 57.75Wh/11.4V, 3 Cells Lithium-ion polymer battery',
      'Power Adaptor': 'Input:100-240V-50/60Hz, Output: 19.0V',
      'Reset Key for recovery': 'NA',
      'Warranty Period': '18 Months Onsite Warranty',
      'Warranty Type': 'Onsite Warranty',
      'Covered in Warranty':
        'Manufacturing Defects, Physical Damage not covered',
      'Included in Box': 'Laptop, Power Cord, Adapter, User manual, Laptop Bag',
      'Manufacturer Name': 'Ention™ Technology and Services Pvt. Ltd.',
      Country: 'Make in India',
    },
    pdf: '/assets/E1 intel J4105.pdf',
  },
];

export default products;
