const services = [
    "Select Service",
    "Sole Proprietorship",
    "Partnership Firm",
    "OPC",
    "LLP",
    "Private Limited Company",
    "Public Limited Company",
    "Producer Company",
    "Nidhi Company",
    "Startup Registration",
    "MSME registration",
    "FSSAI registration",
    "BIS registration",
    "Iso certification",
    "Shop and establishment",
    "PF registration",
    "ESI registration",
    "IEC registration",
    "Trademark search report",
    "Trademark registration",
    "Reply to objection",
    "Trademark renewal",
    "Trademark watch",
    "Assignment of Trademark",
    "Conversion of proprietorship into company",
    "Conversion of partnership firm into company",
    "Conversion of OPC into company",
    "Conversion of LLP into company",
    " PAN and TAN",
    " GST registration",
    "GST Return",
    "ITR",
    "TDS Return",
    "Society registration ",
    "Trust registration",
    "Sec 8 company registration",
    "Darpan Registration",
    "Sec 12A and Sec80G registration ",
    "Patent Search",
    "Patent Provisional Application",
    "Patent Permanent Application",
    "Copy Right Registration",



];
  
export default services;